title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/brandon-smeltz/">LinkedIn</a> 
  <br>
  <a href="https://docs.google.com/document/d/1BIOQTY2gkfEoMh-dkH_sTslUdJDv8r5hzTp9YgCpX_A/edit">Resume</a>   
  <br>
  <a href="https://github.com/Brandon4106">GitHub</a>   
  
theme: jekyll-theme-minimal
